# INF4039 Deep Learning Systems / Giliojo mokymo sistemų taikymai
**LAB1** 
**Single layer perceptron**

This practical will help you to understand the influence of the basic single-layer perceptron (SLP) parameters on the classification accuracy. 

## Import NumPy
NumPy library - the most popular choice for linear algebra operations.

In [2]:
import numpy as np

## Create training set of Inputs and corresponding Outputs
There are 7 vectors in our Input, and 7 values as ONE vector in our Output.

Input of [0, 0, 1, 0] => Output of [0]
Input of [1, 1, 1, 0] => Output of [1]
etc.

In [3]:
ts_inputs = np.array([[0,0,1,0],
                      [1,1,1,0],
                      [1,0,1,1],
                      [0,1,1,1],
                      [0,1,0,1],
                      [1,1,1,1],
                      [0,0,0,0]])

ts_outputs = np.array([[0,1,1,0,0,1,0]]).T

### Create a class to construct Perceptron and Initialize Synapses
Random values of Synapse Weights are assigned. NumPy’s random number generator is used for this.

In [4]:
class Perceptron():
    def __init__(self):
        self.synapse_weights = np.random.rand(4,1)

### Define Sigmoid function

In [5]:
def sigmoid(self, x):
    return 1 / (1 + np.exp(-x))

### Define the derivative of Sigmoid function

In [6]:
def sigmoid_deriv(self, x):
     return np.exp(-x)/((1 + np.exp(-x))**2)

### The training function
The function train take the parameters:
1. **inputs**; our input array defined above
2. **real_outputs**; the expected output array, also defined above
3. **its**; number of iterations to loop through
4. **lr**; learning rate

In [7]:
def train(self, inputs, real_outputs, its, lr):
    
    delta_weights = np.zeros((4,7))
    
    for iteration in (range(its)):
        
        # Forward Pass
        z = np.dot(inputs, self.syn_weights)
        activation = self.sigmoid(z)
        
        # Backward Pass
        for i in range(7):
            cost = (activation[i] - real_outputs[i])**2
            cost_prime = 2*(activation[i] - real_outputs[i])
            for n in range(4):
                delta_weights[n][i] = cost_prime * inputs[i][n] * self.sigmoid_deriv(z[i])
                
    delta_avg = np.array([np.average(delta_weights, axis=1)]).T
    self.syn_weights = self.syn_weights - delta_avg*lr

### Back-Propagation
This function to allow us to evaluate our model’s predicted outputs given our inputs and the learned synapse weighting.

In [8]:
def results(self, inputs):
     return self.sigmoid(np.dot(inputs, self.syn_weights))

## Completed code

In [9]:
import numpy as np

class Perceptron():
    def __init__(self):
        self.syn_weights = np.random.rand(4,1)

    def sigmoid(self, x):
        return (1 / (1 + np.exp(-x)))

    def sigmoid_deriv(self, x):
        return np.exp(-x)/((1 + np.exp(-x))**2)

    def train(self, inputs, real_outputs, its, lr):

        delta_weights = np.zeros((4,7))

        for iteration in (range(its)):

            # forward pass
            z = np.dot(inputs, self.syn_weights)
            activation = self.sigmoid(z)

            # back pass
            for i in range(7):
                cost = (activation[i] - real_outputs[i])**2
                cost_prime = 2*(activation[i] - real_outputs[i])
                for n in range(4):
                    delta_weights[n][i] = cost_prime * inputs[i][n] * self.sigmoid_deriv(z[i])

            delta_avg = np.array([np.average(delta_weights, axis=1)]).T
            self.syn_weights = self.syn_weights - delta_avg*lr

    def results(self, inputs):
        return self.sigmoid(np.dot(inputs, self.syn_weights))


if __name__ == "__main__":

    ts_input = np.array([[0,0,1,0],
                         [1,1,1,0],
                         [1,0,1,1],
                         [0,1,1,1],
                         [0,1,0,1],
                         [1,1,1,1],
                         [0,0,0,0]])

    ts_output = np.array([[0,1,1,0,0,1,0]]).T # First Value of Input = output

    testing_data = np.array([[0,1,1,0],
                             [0,0,0,1],
                             [0,1,0,0],
                             [1,0,0,1],
                             [1,0,0,0],
                             [1,1,0,0],
                             [1,0,1,0]])

    lr = 10 # Learning Rate
    steps = 10000
    perceptron = Perceptron() # Initialize a perceptron
    perceptron.train(ts_input, ts_output, steps, lr) # Train the perceptron

    results = []
    for x in (range(len(testing_data))):
        run = testing_data[x]
        trial = perceptron.results(run)
        results.append(trial.tolist())
    print("results")
    print(results)
    print(np.ravel(np.rint(results))) # View rounded results
    print(perceptron.syn_weights)

results
[[0.0007514023865391206], [0.08286357409809664], [0.08089546192719621], [0.9999944943249781], [0.9999995025579814], [0.9999943482755488], [0.9999417792730834]]
[0. 0. 0. 1. 1. 1. 1.]
[[14.51378634]
 [-2.43024214]
 [-4.76257542]
 [-2.40406067]]


## Comments

Output values will never reach exactly 0 or 1 since they are passed through a Sigmoid function

In [10]:
print(results)

[[0.0007514023865391206], [0.08286357409809664], [0.08089546192719621], [0.9999944943249781], [0.9999995025579814], [0.9999943482755488], [0.9999417792730834]]


View rounded results

In [11]:
print(np.ravel(np.rint(results)))

[0. 0. 0. 1. 1. 1. 1.]


Printing our Synapse Weights serves as a final check to see that our weight is largest for the first Synapse.

In [12]:
print(perceptron.syn_weights)

[[14.51378634]
 [-2.43024214]
 [-4.76257542]
 [-2.40406067]]
